#!/bin/bash

typeset -u layer
layer=D
wkrs=1
if [[ $# -eq 1 ]]; then 
	layer=$1
fi

if [[ $# -eq 2 ]]; then 
	wkrs=$2
	layer=$1
fi

printf "***************************************************\n"
printf "***\n"
printf "*** Setting up for Workers : $wkrs \n"
printf "*** Pointing at the Layer  : ${layer} \n"
printf "***\n"
cp ~/docker-compose.yml.${layer}.$wkrs.BATCH ~/HTAP-Batch/docker-compose.yml

cd ~/HTAP-Batch

docker-compose up --remove-orphans
